name: OpenAI API Handler

on:
  workflow_dispatch:
    inputs:
      playerInput:
        description: 'Player Input'
        required: true
      gameState:
        description: 'Game State'
        required: true

jobs:
  process-input:
    runs-on: ubuntu-latest
    steps:
      - name: Call OpenAI API
        env:
          OPENAI_API: ${{ secrets.OPENAI_API }}
        run: |
          echo "Player Input: ${{ github.event.inputs.playerInput }}"
          echo "Game State: ${{ github.event.inputs.gameState }}"

          RESPONSE=$(curl -X POST https://api.openai.com/v1/completions \
          -H "Authorization: Bearer $OPENAI_API" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-3.5-turbo",
            "prompt": "You are in a text-based adventure game. The player has the following abilities and inventory: ${{ github.event.inputs.gameState }}. The player\'s input is: \"${{ github.event.inputs.playerInput }}\". Generate a context-aware story continuation.",
            "max_tokens": 150,
            "temperature": 0.7
          }')

          echo "Response: $RESPONSE"
